### ISSUE TITLE
Internal link go no where

### ISSUE THREAD

**Issue by lboitier1** [RevenueCat/revenuecat-docs#511]
Here : https://www.revenuecat.com/docs/customer-info
In "Get User Information", go to the row talking about Entitlements.

There's a link on the "See more below" text, but it is redirecting me in a blank page.

Thanks !

![Capture d’écran 2023-11-22 à 14 31 41](https://github.com/RevenueCat/revenuecat-docs/assets/62649723/6790f51a-6a04-42d1-9600-434ceeef30c9)

**Comment by rglanz-rc** [comment]
Hi @lboitier1, thanks for the heads up! I've fixed this (the link just takes you down to the next section on the same page)
